DELIMITER $$
CREATE PROCEDURE DNCOMMERCE.CRIAR_VENDA(
	IN P_PEDIDO_ID INTEGER,
    IN P_CLIENTE_ID INTEGER,
    IN P_PRODUTO_ID INTEGER,
    IN P_QUANTIDADE INTEGER,
    IN P_VALOR_TOTAL DECIMAL(13,2),
    IN P_DATA DATETIME,
    IN P_VLR_FRETE DECIMAL(13,2),
    IN P_CUPOM VARCHAR(150),
    IN P_FORMA_PAGTO INTEGER,
    OUT R_RESULTADO VARCHAR(250)
) 
BEGIN
    DECLARE L_VALOR_TOTAL_PEDIDO DECIMAL(13,2) DEFAULT 0;
    DECLARE L_QUANTIDADE_ATUAL INTEGER DEFAULT 0;
    DECLARE L_QUANTIDADE_NOVA INTEGER DEFAULT 0;
    
    SELECT QUANTIDADE INTO L_QUANTIDADE_ATUAL
    FROM TBL_ESTOQUE
    WHERE PRODUTO_ID = P_PRODUTO_ID
    ;
    
    SET L_QUANTIDADE_NOVA = L_QUANTIDADE_ATUAL - P_QUANTIDADE;
    
    IF (L_QUANTIDADE_ATUAL = 0) THEN
		RETURN ('SEM ESTOQUE DO PRODUTO!');
    
    ELSEIF (L_QUANTIDADE_ATUAL - P_QUANTIDADE) < 0 THEN
		RETURN ('QUANTIDADE MAIOR QUE O ESTOQUE DISPONÍVEL!');
        
	ELSE
		UPDATE TBL_ESTOQUE
		SET QUANTIDADE = L_QUANTIDADE_NOVA
		WHERE PRODUTO_ID = P_PRODUTO_ID
		;
    
    END IF;
    
    INSERT INTO DNCOMMERCE.TBL_PEDIDO
	(ID,
    CLIENTE_ID,
    PRODUTO_ID,
    QUANTIDADE,
	VALOR_TOTAL,
	DATA
	)
	VALUES
	(P_PEDIDO_ID,
	P_CLIENTE_ID,
	P_PRODUTO_ID,
	P_QUANTIDADE,
	P_VALOR_TOTAL,
    P_DATA)
    ;
    
    SELECT SUM(VALOR_TOTAL) INTO L_VALOR_TOTAL_PEDIDO
	FROM TBL_PEDIDO
	WHERE ID = P_PEDIDO_ID
	;
    
    INSERT INTO dncommerce.tbl_venda
	(PEDIDO_ID,
	FORMA_PAGTO_ID,
	VALOR_FRETE,
	VALOR_TOTAL,
	CUPOM,
	DATA	
	)
	VALUES
	(P_PEDIDO_ID,
	P_FORMA_PAGTO,
	P_VLR_FRETE,
	(L_VALOR_TOTAL_PEDIDO + P_VLR_FRETE),
	P_CUPOM,
	P_DATA)
	;

    RETURN ('PEDIDO REALIZADO!');
END
$$ DELIMITER ;